//
//Palu Wiki AI Service - gRPC Protocol Buffer Definition
//AI微服务gRPC接口定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: protos/ai_service.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 块类型枚举
type ChunkType int32

const (
	ChunkType_CONTENT  ChunkType = 0 // 内容块
	ChunkType_METADATA ChunkType = 1 // 元数据块
	ChunkType_ERROR    ChunkType = 2 // 错误块
	ChunkType_FINAL    ChunkType = 3 // 结束块
)

// Enum value maps for ChunkType.
var (
	ChunkType_name = map[int32]string{
		0: "CONTENT",
		1: "METADATA",
		2: "ERROR",
		3: "FINAL",
	}
	ChunkType_value = map[string]int32{
		"CONTENT":  0,
		"METADATA": 1,
		"ERROR":    2,
		"FINAL":    3,
	}
)

func (x ChunkType) Enum() *ChunkType {
	p := new(ChunkType)
	*p = x
	return p
}

func (x ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ai_service_proto_enumTypes[0].Descriptor()
}

func (ChunkType) Type() protoreflect.EnumType {
	return &file_protos_ai_service_proto_enumTypes[0]
}

func (x ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkType.Descriptor instead.
func (ChunkType) EnumDescriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{0}
}

// 健康状态枚举
type HealthStatus int32

const (
	HealthStatus_SERVING         HealthStatus = 0 // 服务正常
	HealthStatus_NOT_SERVING     HealthStatus = 1 // 服务不可用
	HealthStatus_UNKNOWN         HealthStatus = 2 // 状态未知
	HealthStatus_SERVICE_UNKNOWN HealthStatus = 3 // 服务未知
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "SERVING",
		1: "NOT_SERVING",
		2: "UNKNOWN",
		3: "SERVICE_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"SERVING":         0,
		"NOT_SERVING":     1,
		"UNKNOWN":         2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ai_service_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_protos_ai_service_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{1}
}

// 内容生成请求
type ContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                               // 生成提示
	Topic         *string                `protobuf:"bytes,2,opt,name=topic,proto3,oneof" json:"topic,omitempty"`                                                                           // 主题
	MaxLength     *int32                 `protobuf:"varint,3,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`                                                 // 最大长度
	UserId        *string                `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`                                                           // 用户ID
	Provider      *string                `protobuf:"bytes,5,opt,name=provider,proto3,oneof" json:"provider,omitempty"`                                                                     // 指定AI提供商
	Temperature   *float32               `protobuf:"fixed32,6,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`                                                             // 创造性 0.0-2.0
	UseRag        *bool                  `protobuf:"varint,7,opt,name=use_rag,json=useRag,proto3,oneof" json:"use_rag,omitempty"`                                                          // 是否使用RAG增强
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRequest) Reset() {
	*x = ContentRequest{}
	mi := &file_protos_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRequest) ProtoMessage() {}

func (x *ContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRequest.ProtoReflect.Descriptor instead.
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *ContentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ContentRequest) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *ContentRequest) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *ContentRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ContentRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *ContentRequest) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ContentRequest) GetUseRag() bool {
	if x != nil && x.UseRag != nil {
		return *x.UseRag
	}
	return false
}

func (x *ContentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 文章生成请求
type ArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                                                                 // 文章标题
	Category      *string                `protobuf:"bytes,2,opt,name=category,proto3,oneof" json:"category,omitempty"`                                                                     // 分类
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`                                                                           // 关键词
	Length        *int32                 `protobuf:"varint,4,opt,name=length,proto3,oneof" json:"length,omitempty"`                                                                        // 文章长度
	UserId        *string                `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`                                                           // 用户ID
	Provider      *string                `protobuf:"bytes,6,opt,name=provider,proto3,oneof" json:"provider,omitempty"`                                                                     // 指定AI提供商
	UseRag        *bool                  `protobuf:"varint,7,opt,name=use_rag,json=useRag,proto3,oneof" json:"use_rag,omitempty"`                                                          // 是否使用RAG
	WritingStyle  *string                `protobuf:"bytes,8,opt,name=writing_style,json=writingStyle,proto3,oneof" json:"writing_style,omitempty"`                                         // 写作风格
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleRequest) Reset() {
	*x = ArticleRequest{}
	mi := &file_protos_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleRequest) ProtoMessage() {}

func (x *ArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleRequest.ProtoReflect.Descriptor instead.
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ArticleRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ArticleRequest) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *ArticleRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ArticleRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *ArticleRequest) GetUseRag() bool {
	if x != nil && x.UseRag != nil {
		return *x.UseRag
	}
	return false
}

func (x *ArticleRequest) GetWritingStyle() string {
	if x != nil && x.WritingStyle != nil {
		return *x.WritingStyle
	}
	return ""
}

func (x *ArticleRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 向量搜索请求
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                                                               // 搜索查询
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                                                                        // 返回数量
	Threshold     *float32               `protobuf:"fixed32,3,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`                                                               // 相似度阈值
	Collection    *string                `protobuf:"bytes,4,opt,name=collection,proto3,oneof" json:"collection,omitempty"`                                                               // 搜索集合
	Filters       map[string]string      `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 过滤条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_protos_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *SearchRequest) GetThreshold() float32 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *SearchRequest) GetCollection() string {
	if x != nil && x.Collection != nil {
		return *x.Collection
	}
	return ""
}

func (x *SearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// 批量处理请求
type BatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       []*ContentRequest      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`                                          // 批量请求
	MaxConcurrent  *int32                 `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3,oneof" json:"max_concurrent,omitempty"`    // 最大并发数
	TimeoutSeconds *int32                 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"` // 超时时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_protos_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchRequest) GetRequests() []*ContentRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchRequest) GetMaxConcurrent() int32 {
	if x != nil && x.MaxConcurrent != nil {
		return *x.MaxConcurrent
	}
	return 0
}

func (x *BatchRequest) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

// 统计信息请求
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeModels *bool                  `protobuf:"varint,1,opt,name=include_models,json=includeModels,proto3,oneof" json:"include_models,omitempty"` // 包含模型统计
	IncludeUsage  *bool                  `protobuf:"varint,2,opt,name=include_usage,json=includeUsage,proto3,oneof" json:"include_usage,omitempty"`    // 包含使用统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_protos_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *StatsRequest) GetIncludeModels() bool {
	if x != nil && x.IncludeModels != nil {
		return *x.IncludeModels
	}
	return false
}

func (x *StatsRequest) GetIncludeUsage() bool {
	if x != nil && x.IncludeUsage != nil {
		return *x.IncludeUsage
	}
	return false
}

// 健康检查请求
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeepCheck     *bool                  `protobuf:"varint,1,opt,name=deep_check,json=deepCheck,proto3,oneof" json:"deep_check,omitempty"` // 深度检查
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_protos_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthRequest) GetDeepCheck() bool {
	if x != nil && x.DeepCheck != nil {
		return *x.DeepCheck
	}
	return false
}

// 内容生成响应
type ContentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 生成的内容
	Summary        *string                `protobuf:"bytes,2,opt,name=summary,proto3,oneof" json:"summary,omitempty"`                                                                       // 内容摘要
	Tags           []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                   // 标签
	ModelUsed      string                 `protobuf:"bytes,4,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`                                                        // 使用的模型
	TokensUsed     int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`                                                    // 使用的token数量
	GenerationTime float64                `protobuf:"fixed64,6,opt,name=generation_time,json=generationTime,proto3" json:"generation_time,omitempty"`                                       // 生成时间(秒)
	Confidence     *float32               `protobuf:"fixed32,7,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`                                                               // 置信度
	Sources        []string               `protobuf:"bytes,8,rep,name=sources,proto3" json:"sources,omitempty"`                                                                             // RAG来源
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展元数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContentResponse) Reset() {
	*x = ContentResponse{}
	mi := &file_protos_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentResponse) ProtoMessage() {}

func (x *ContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentResponse.ProtoReflect.Descriptor instead.
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *ContentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContentResponse) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *ContentResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ContentResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *ContentResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ContentResponse) GetGenerationTime() float64 {
	if x != nil {
		return x.GenerationTime
	}
	return 0
}

func (x *ContentResponse) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *ContentResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ContentResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 文章生成响应
type ArticleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                                                                  // 文章标题
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                                              // 文章内容
	Summary        string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                                                                              // 文章摘要
	Tags           []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                    // 标签
	Category       *string                `protobuf:"bytes,5,opt,name=category,proto3,oneof" json:"category,omitempty"`                                                                      // 分类
	WordCount      int32                  `protobuf:"varint,6,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`                                                        // 字数统计
	ModelUsed      string                 `protobuf:"bytes,7,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`                                                         // 使用的模型
	TokensUsed     int32                  `protobuf:"varint,8,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`                                                     // 使用的token数量
	GenerationTime float64                `protobuf:"fixed64,9,opt,name=generation_time,json=generationTime,proto3" json:"generation_time,omitempty"`                                        // 生成时间(秒)
	Sources        []string               `protobuf:"bytes,10,rep,name=sources,proto3" json:"sources,omitempty"`                                                                             // RAG来源
	Metadata       map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展元数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArticleResponse) Reset() {
	*x = ArticleResponse{}
	mi := &file_protos_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResponse) ProtoMessage() {}

func (x *ArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResponse.ProtoReflect.Descriptor instead.
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *ArticleResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ArticleResponse) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ArticleResponse) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ArticleResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *ArticleResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ArticleResponse) GetGenerationTime() float64 {
	if x != nil {
		return x.GenerationTime
	}
	return 0
}

func (x *ArticleResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ArticleResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 搜索结果项
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 文档ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                                                                 // 标题
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 内容片段
	Similarity    float32                `protobuf:"fixed32,4,opt,name=similarity,proto3" json:"similarity,omitempty"`                                                                     // 相似度分数
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_protos_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 搜索响应
type SearchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Results        []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                     // 搜索结果
	TotalCount     int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`            // 总结果数
	SearchTime     float64                `protobuf:"fixed64,3,opt,name=search_time,json=searchTime,proto3" json:"search_time,omitempty"`           // 搜索时间(秒)
	QueryProcessed string                 `protobuf:"bytes,4,opt,name=query_processed,json=queryProcessed,proto3" json:"query_processed,omitempty"` // 处理后的查询
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_protos_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchResponse) GetSearchTime() float64 {
	if x != nil {
		return x.SearchTime
	}
	return 0
}

func (x *SearchResponse) GetQueryProcessed() string {
	if x != nil {
		return x.QueryProcessed
	}
	return ""
}

// 流式内容块
type StreamContentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`                                                                                 // 内容块
	Type          ChunkType              `protobuf:"varint,2,opt,name=type,proto3,enum=ai.ChunkType" json:"type,omitempty"`                                                                // 块类型
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`                                                             // 是否为最后一块
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContentChunk) Reset() {
	*x = StreamContentChunk{}
	mi := &file_protos_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContentChunk) ProtoMessage() {}

func (x *StreamContentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContentChunk.ProtoReflect.Descriptor instead.
func (*StreamContentChunk) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{10}
}

func (x *StreamContentChunk) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *StreamContentChunk) GetType() ChunkType {
	if x != nil {
		return x.Type
	}
	return ChunkType_CONTENT
}

func (x *StreamContentChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamContentChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 批量响应
type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                // 批量结果
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	ErrorCount    int32                  `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`       // 错误数量
	TotalTime     float64                `protobuf:"fixed64,4,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`         // 总耗时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_protos_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *BatchResponse) GetResults() []*BatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *BatchResponse) GetTotalTime() float64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

// 批量结果项
type BatchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 请求索引
	// Types that are valid to be assigned to Result:
	//
	//	*BatchResult_Success
	//	*BatchResult_Error
	Result        isBatchResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResult) Reset() {
	*x = BatchResult{}
	mi := &file_protos_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResult) ProtoMessage() {}

func (x *BatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResult.ProtoReflect.Descriptor instead.
func (*BatchResult) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{12}
}

func (x *BatchResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BatchResult) GetResult() isBatchResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BatchResult) GetSuccess() *ContentResponse {
	if x != nil {
		if x, ok := x.Result.(*BatchResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *BatchResult) GetError() *ErrorInfo {
	if x != nil {
		if x, ok := x.Result.(*BatchResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isBatchResult_Result interface {
	isBatchResult_Result()
}

type BatchResult_Success struct {
	Success *ContentResponse `protobuf:"bytes,2,opt,name=success,proto3,oneof"` // 成功结果
}

type BatchResult_Error struct {
	Error *ErrorInfo `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // 错误信息
}

func (*BatchResult_Success) isBatchResult_Result() {}

func (*BatchResult_Error) isBatchResult_Result() {}

// 模型统计
type ModelStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                          // 提供商
	ModelName       string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                       // 模型名称
	RequestsCount   int64                  `protobuf:"varint,3,opt,name=requests_count,json=requestsCount,proto3" json:"requests_count,omitempty"`          // 请求次数
	SuccessRate     float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`               // 成功率
	AvgResponseTime float64                `protobuf:"fixed64,5,opt,name=avg_response_time,json=avgResponseTime,proto3" json:"avg_response_time,omitempty"` // 平均响应时间
	TotalTokens     int64                  `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`                // 总token使用量
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                              // 模型状态
	LastUsed        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`                          // 最后使用时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelStats) Reset() {
	*x = ModelStats{}
	mi := &file_protos_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStats) ProtoMessage() {}

func (x *ModelStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStats.ProtoReflect.Descriptor instead.
func (*ModelStats) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *ModelStats) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelStats) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelStats) GetRequestsCount() int64 {
	if x != nil {
		return x.RequestsCount
	}
	return 0
}

func (x *ModelStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ModelStats) GetAvgResponseTime() float64 {
	if x != nil {
		return x.AvgResponseTime
	}
	return 0
}

func (x *ModelStats) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ModelStats) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModelStats) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

// 服务统计响应
type StatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uptime          float64                `protobuf:"fixed64,1,opt,name=uptime,proto3" json:"uptime,omitempty"`                                            // 运行时间(秒)
	TotalRequests   int64                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`          // 总请求数
	SuccessRequests int64                  `protobuf:"varint,3,opt,name=success_requests,json=successRequests,proto3" json:"success_requests,omitempty"`    // 成功请求数
	ErrorRequests   int64                  `protobuf:"varint,4,opt,name=error_requests,json=errorRequests,proto3" json:"error_requests,omitempty"`          // 错误请求数
	AvgResponseTime float64                `protobuf:"fixed64,5,opt,name=avg_response_time,json=avgResponseTime,proto3" json:"avg_response_time,omitempty"` // 平均响应时间
	Models          []*ModelStats          `protobuf:"bytes,6,rep,name=models,proto3" json:"models,omitempty"`                                              // 模型统计
	MemoryUsage     float64                `protobuf:"fixed64,7,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`               // 内存使用(MB)
	VectorDbSize    int32                  `protobuf:"varint,8,opt,name=vector_db_size,json=vectorDbSize,proto3" json:"vector_db_size,omitempty"`           // 向量库大小
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                       // 启动时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_protos_ai_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{14}
}

func (x *StatsResponse) GetUptime() float64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *StatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatsResponse) GetSuccessRequests() int64 {
	if x != nil {
		return x.SuccessRequests
	}
	return 0
}

func (x *StatsResponse) GetErrorRequests() int64 {
	if x != nil {
		return x.ErrorRequests
	}
	return 0
}

func (x *StatsResponse) GetAvgResponseTime() float64 {
	if x != nil {
		return x.AvgResponseTime
	}
	return 0
}

func (x *StatsResponse) GetModels() []*ModelStats {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *StatsResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *StatsResponse) GetVectorDbSize() int32 {
	if x != nil {
		return x.VectorDbSize
	}
	return 0
}

func (x *StatsResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=ai.HealthStatus" json:"status,omitempty"`        // 健康状态
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名称
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                            // 版本号
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // 检查时间
	Components    []*ComponentHealth     `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty"`                      // 组件健康状态
	Message       *string                `protobuf:"bytes,6,opt,name=message,proto3,oneof" json:"message,omitempty"`                      // 额外信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_protos_ai_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_SERVING
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// 组件健康状态
type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // 组件名称
	Status        HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=ai.HealthStatus" json:"status,omitempty"`  // 组件状态
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`                // 状态信息
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"` // 最后检查时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_protos_ai_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{16}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_SERVING
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ComponentHealth) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

// 错误信息
type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`             // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`       // 错误信息
	Details       *string                `protobuf:"bytes,3,opt,name=details,proto3,oneof" json:"details,omitempty"` // 错误详情
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`  // 是否可重试
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`   // 错误时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_protos_ai_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_protos_ai_service_proto_rawDescGZIP(), []int{17}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *ErrorInfo) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_protos_ai_service_proto protoreflect.FileDescriptor

const file_protos_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x17protos/ai_service.proto\x12\x02ai\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x03\n" +
	"\x0eContentRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x19\n" +
	"\x05topic\x18\x02 \x01(\tH\x00R\x05topic\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x03 \x01(\x05H\x01R\tmaxLength\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\tH\x02R\x06userId\x88\x01\x01\x12\x1f\n" +
	"\bprovider\x18\x05 \x01(\tH\x03R\bprovider\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x06 \x01(\x02H\x04R\vtemperature\x88\x01\x01\x12\x1c\n" +
	"\ause_rag\x18\a \x01(\bH\x05R\x06useRag\x88\x01\x01\x12<\n" +
	"\bmetadata\x18\b \x03(\v2 .ai.ContentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_topicB\r\n" +
	"\v_max_lengthB\n" +
	"\n" +
	"\b_user_idB\v\n" +
	"\t_providerB\x0e\n" +
	"\f_temperatureB\n" +
	"\n" +
	"\b_use_rag\"\xd1\x03\n" +
	"\x0eArticleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\bcategory\x18\x02 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12\x1b\n" +
	"\x06length\x18\x04 \x01(\x05H\x01R\x06length\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x05 \x01(\tH\x02R\x06userId\x88\x01\x01\x12\x1f\n" +
	"\bprovider\x18\x06 \x01(\tH\x03R\bprovider\x88\x01\x01\x12\x1c\n" +
	"\ause_rag\x18\a \x01(\bH\x04R\x06useRag\x88\x01\x01\x12(\n" +
	"\rwriting_style\x18\b \x01(\tH\x05R\fwritingStyle\x88\x01\x01\x12<\n" +
	"\bmetadata\x18\t \x03(\v2 .ai.ArticleRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_categoryB\t\n" +
	"\a_lengthB\n" +
	"\n" +
	"\b_user_idB\v\n" +
	"\t_providerB\n" +
	"\n" +
	"\b_use_ragB\x10\n" +
	"\x0e_writing_style\"\xa5\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12!\n" +
	"\tthreshold\x18\x03 \x01(\x02H\x01R\tthreshold\x88\x01\x01\x12#\n" +
	"\n" +
	"collection\x18\x04 \x01(\tH\x02R\n" +
	"collection\x88\x01\x01\x128\n" +
	"\afilters\x18\x05 \x03(\v2\x1e.ai.SearchRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_limitB\f\n" +
	"\n" +
	"_thresholdB\r\n" +
	"\v_collection\"\xbf\x01\n" +
	"\fBatchRequest\x12.\n" +
	"\brequests\x18\x01 \x03(\v2\x12.ai.ContentRequestR\brequests\x12*\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05H\x00R\rmaxConcurrent\x88\x01\x01\x12,\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05H\x01R\x0etimeoutSeconds\x88\x01\x01B\x11\n" +
	"\x0f_max_concurrentB\x12\n" +
	"\x10_timeout_seconds\"\x89\x01\n" +
	"\fStatsRequest\x12*\n" +
	"\x0einclude_models\x18\x01 \x01(\bH\x00R\rincludeModels\x88\x01\x01\x12(\n" +
	"\rinclude_usage\x18\x02 \x01(\bH\x01R\fincludeUsage\x88\x01\x01B\x11\n" +
	"\x0f_include_modelsB\x10\n" +
	"\x0e_include_usage\"B\n" +
	"\rHealthRequest\x12\"\n" +
	"\n" +
	"deep_check\x18\x01 \x01(\bH\x00R\tdeepCheck\x88\x01\x01B\r\n" +
	"\v_deep_check\"\x9d\x03\n" +
	"\x0fContentResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\asummary\x18\x02 \x01(\tH\x00R\asummary\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"model_used\x18\x04 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\x12'\n" +
	"\x0fgeneration_time\x18\x06 \x01(\x01R\x0egenerationTime\x12#\n" +
	"\n" +
	"confidence\x18\a \x01(\x02H\x01R\n" +
	"confidence\x88\x01\x01\x12\x18\n" +
	"\asources\x18\b \x03(\tR\asources\x12=\n" +
	"\bmetadata\x18\t \x03(\v2!.ai.ContentResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_summaryB\r\n" +
	"\v_confidence\"\xbb\x03\n" +
	"\x0fArticleResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1f\n" +
	"\bcategory\x18\x05 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"word_count\x18\x06 \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"model_used\x18\a \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\b \x01(\x05R\n" +
	"tokensUsed\x12'\n" +
	"\x0fgeneration_time\x18\t \x01(\x01R\x0egenerationTime\x12\x18\n" +
	"\asources\x18\n" +
	" \x03(\tR\asources\x12=\n" +
	"\bmetadata\x18\v \x03(\v2!.ai.ArticleResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_category\"\xe7\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"similarity\x18\x04 \x01(\x02R\n" +
	"similarity\x12:\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1e.ai.SearchResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x0eSearchResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.ai.SearchResultR\aresults\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vsearch_time\x18\x03 \x01(\x01R\n" +
	"searchTime\x12'\n" +
	"\x0fquery_processed\x18\x04 \x01(\tR\x0equeryProcessed\"\xe7\x01\n" +
	"\x12StreamContentChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.ai.ChunkTypeR\x04type\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.ai.StreamContentChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\rBatchResponse\x12)\n" +
	"\aresults\x18\x01 \x03(\v2\x0f.ai.BatchResultR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x05R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"total_time\x18\x04 \x01(\x01R\ttotalTime\"\x85\x01\n" +
	"\vBatchResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12/\n" +
	"\asuccess\x18\x02 \x01(\v2\x13.ai.ContentResponseH\x00R\asuccess\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\r.ai.ErrorInfoH\x00R\x05errorB\b\n" +
	"\x06result\"\xb1\x02\n" +
	"\n" +
	"ModelStats\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12%\n" +
	"\x0erequests_count\x18\x03 \x01(\x03R\rrequestsCount\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12*\n" +
	"\x11avg_response_time\x18\x05 \x01(\x01R\x0favgResponseTime\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x03R\vtotalTokens\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x127\n" +
	"\tlast_used\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\"\xf8\x02\n" +
	"\rStatsResponse\x12\x16\n" +
	"\x06uptime\x18\x01 \x01(\x01R\x06uptime\x12%\n" +
	"\x0etotal_requests\x18\x02 \x01(\x03R\rtotalRequests\x12)\n" +
	"\x10success_requests\x18\x03 \x01(\x03R\x0fsuccessRequests\x12%\n" +
	"\x0eerror_requests\x18\x04 \x01(\x03R\rerrorRequests\x12*\n" +
	"\x11avg_response_time\x18\x05 \x01(\x01R\x0favgResponseTime\x12&\n" +
	"\x06models\x18\x06 \x03(\v2\x0e.ai.ModelStatsR\x06models\x12!\n" +
	"\fmemory_usage\x18\a \x01(\x01R\vmemoryUsage\x12$\n" +
	"\x0evector_db_size\x18\b \x01(\x05R\fvectorDbSize\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\x91\x02\n" +
	"\x0eHealthResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.ai.HealthStatusR\x06status\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\n" +
	"components\x18\x05 \x03(\v2\x13.ai.ComponentHealthR\n" +
	"components\x12\x1d\n" +
	"\amessage\x18\x06 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\xb5\x01\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.ai.HealthStatusR\x06status\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01\x129\n" +
	"\n" +
	"last_check\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheckB\n" +
	"\n" +
	"\b_message\"\xbc\x01\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\adetails\x18\x03 \x01(\tH\x00R\adetails\x88\x01\x01\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\n" +
	"\n" +
	"\b_details*<\n" +
	"\tChunkType\x12\v\n" +
	"\aCONTENT\x10\x00\x12\f\n" +
	"\bMETADATA\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\t\n" +
	"\x05FINAL\x10\x03*N\n" +
	"\fHealthStatus\x12\v\n" +
	"\aSERVING\x10\x00\x12\x0f\n" +
	"\vNOT_SERVING\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\xa6\x03\n" +
	"\tAIService\x12:\n" +
	"\x0fGenerateContent\x12\x12.ai.ContentRequest\x1a\x13.ai.ContentResponse\x12:\n" +
	"\x0fGenerateArticle\x12\x12.ai.ArticleRequest\x1a\x13.ai.ArticleResponse\x126\n" +
	"\rSearchSimilar\x12\x11.ai.SearchRequest\x1a\x12.ai.SearchResponse\x12E\n" +
	"\x15StreamGenerateContent\x12\x12.ai.ContentRequest\x1a\x16.ai.StreamContentChunk0\x01\x124\n" +
	"\rBatchGenerate\x12\x10.ai.BatchRequest\x1a\x11.ai.BatchResponse\x126\n" +
	"\x0fGetServiceStats\x12\x10.ai.StatsRequest\x1a\x11.ai.StatsResponse\x124\n" +
	"\vHealthCheck\x12\x11.ai.HealthRequest\x1a\x12.ai.HealthResponseB\x17Z\x15palu-wiki/pkg/grpc/aib\x06proto3"

var (
	file_protos_ai_service_proto_rawDescOnce sync.Once
	file_protos_ai_service_proto_rawDescData []byte
)

func file_protos_ai_service_proto_rawDescGZIP() []byte {
	file_protos_ai_service_proto_rawDescOnce.Do(func() {
		file_protos_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ai_service_proto_rawDesc), len(file_protos_ai_service_proto_rawDesc)))
	})
	return file_protos_ai_service_proto_rawDescData
}

var file_protos_ai_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_protos_ai_service_proto_goTypes = []any{
	(ChunkType)(0),                // 0: ai.ChunkType
	(HealthStatus)(0),             // 1: ai.HealthStatus
	(*ContentRequest)(nil),        // 2: ai.ContentRequest
	(*ArticleRequest)(nil),        // 3: ai.ArticleRequest
	(*SearchRequest)(nil),         // 4: ai.SearchRequest
	(*BatchRequest)(nil),          // 5: ai.BatchRequest
	(*StatsRequest)(nil),          // 6: ai.StatsRequest
	(*HealthRequest)(nil),         // 7: ai.HealthRequest
	(*ContentResponse)(nil),       // 8: ai.ContentResponse
	(*ArticleResponse)(nil),       // 9: ai.ArticleResponse
	(*SearchResult)(nil),          // 10: ai.SearchResult
	(*SearchResponse)(nil),        // 11: ai.SearchResponse
	(*StreamContentChunk)(nil),    // 12: ai.StreamContentChunk
	(*BatchResponse)(nil),         // 13: ai.BatchResponse
	(*BatchResult)(nil),           // 14: ai.BatchResult
	(*ModelStats)(nil),            // 15: ai.ModelStats
	(*StatsResponse)(nil),         // 16: ai.StatsResponse
	(*HealthResponse)(nil),        // 17: ai.HealthResponse
	(*ComponentHealth)(nil),       // 18: ai.ComponentHealth
	(*ErrorInfo)(nil),             // 19: ai.ErrorInfo
	nil,                           // 20: ai.ContentRequest.MetadataEntry
	nil,                           // 21: ai.ArticleRequest.MetadataEntry
	nil,                           // 22: ai.SearchRequest.FiltersEntry
	nil,                           // 23: ai.ContentResponse.MetadataEntry
	nil,                           // 24: ai.ArticleResponse.MetadataEntry
	nil,                           // 25: ai.SearchResult.MetadataEntry
	nil,                           // 26: ai.StreamContentChunk.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_protos_ai_service_proto_depIdxs = []int32{
	20, // 0: ai.ContentRequest.metadata:type_name -> ai.ContentRequest.MetadataEntry
	21, // 1: ai.ArticleRequest.metadata:type_name -> ai.ArticleRequest.MetadataEntry
	22, // 2: ai.SearchRequest.filters:type_name -> ai.SearchRequest.FiltersEntry
	2,  // 3: ai.BatchRequest.requests:type_name -> ai.ContentRequest
	23, // 4: ai.ContentResponse.metadata:type_name -> ai.ContentResponse.MetadataEntry
	24, // 5: ai.ArticleResponse.metadata:type_name -> ai.ArticleResponse.MetadataEntry
	25, // 6: ai.SearchResult.metadata:type_name -> ai.SearchResult.MetadataEntry
	10, // 7: ai.SearchResponse.results:type_name -> ai.SearchResult
	0,  // 8: ai.StreamContentChunk.type:type_name -> ai.ChunkType
	26, // 9: ai.StreamContentChunk.metadata:type_name -> ai.StreamContentChunk.MetadataEntry
	14, // 10: ai.BatchResponse.results:type_name -> ai.BatchResult
	8,  // 11: ai.BatchResult.success:type_name -> ai.ContentResponse
	19, // 12: ai.BatchResult.error:type_name -> ai.ErrorInfo
	27, // 13: ai.ModelStats.last_used:type_name -> google.protobuf.Timestamp
	15, // 14: ai.StatsResponse.models:type_name -> ai.ModelStats
	27, // 15: ai.StatsResponse.start_time:type_name -> google.protobuf.Timestamp
	1,  // 16: ai.HealthResponse.status:type_name -> ai.HealthStatus
	27, // 17: ai.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	18, // 18: ai.HealthResponse.components:type_name -> ai.ComponentHealth
	1,  // 19: ai.ComponentHealth.status:type_name -> ai.HealthStatus
	27, // 20: ai.ComponentHealth.last_check:type_name -> google.protobuf.Timestamp
	27, // 21: ai.ErrorInfo.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 22: ai.AIService.GenerateContent:input_type -> ai.ContentRequest
	3,  // 23: ai.AIService.GenerateArticle:input_type -> ai.ArticleRequest
	4,  // 24: ai.AIService.SearchSimilar:input_type -> ai.SearchRequest
	2,  // 25: ai.AIService.StreamGenerateContent:input_type -> ai.ContentRequest
	5,  // 26: ai.AIService.BatchGenerate:input_type -> ai.BatchRequest
	6,  // 27: ai.AIService.GetServiceStats:input_type -> ai.StatsRequest
	7,  // 28: ai.AIService.HealthCheck:input_type -> ai.HealthRequest
	8,  // 29: ai.AIService.GenerateContent:output_type -> ai.ContentResponse
	9,  // 30: ai.AIService.GenerateArticle:output_type -> ai.ArticleResponse
	11, // 31: ai.AIService.SearchSimilar:output_type -> ai.SearchResponse
	12, // 32: ai.AIService.StreamGenerateContent:output_type -> ai.StreamContentChunk
	13, // 33: ai.AIService.BatchGenerate:output_type -> ai.BatchResponse
	16, // 34: ai.AIService.GetServiceStats:output_type -> ai.StatsResponse
	17, // 35: ai.AIService.HealthCheck:output_type -> ai.HealthResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_protos_ai_service_proto_init() }
func file_protos_ai_service_proto_init() {
	if File_protos_ai_service_proto != nil {
		return
	}
	file_protos_ai_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[12].OneofWrappers = []any{
		(*BatchResult_Success)(nil),
		(*BatchResult_Error)(nil),
	}
	file_protos_ai_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[16].OneofWrappers = []any{}
	file_protos_ai_service_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ai_service_proto_rawDesc), len(file_protos_ai_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ai_service_proto_goTypes,
		DependencyIndexes: file_protos_ai_service_proto_depIdxs,
		EnumInfos:         file_protos_ai_service_proto_enumTypes,
		MessageInfos:      file_protos_ai_service_proto_msgTypes,
	}.Build()
	File_protos_ai_service_proto = out.File
	file_protos_ai_service_proto_goTypes = nil
	file_protos_ai_service_proto_depIdxs = nil
}
